---
baseurl: "/"
DefaultContentLanguage: "zh-cn"
hasCJKLanguage: true
languageCode: "zh-cn"
title: "w1100n"
theme: "even"
metaDataFormat: "yaml"
algolia:
  index: "blog"
  key: ${{ secrets.algolia_key }}
  appID: ${{ secrets.algolia_appid }}
---
