---
baseurl: "/"
DefaultContentLanguage: "zh-cn"
hasCJKLanguage: true
languageCode: "zh-cn"
title: "w1100n blog"
theme: "even"
metaDataFormat: "yaml"
algolia:
  index: "blog"
  key: "key0"
  appID: "appid0"
---
