name: github pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1  # v2 does not have submodules option now
        with:
          submodules: true
      
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.70.0'
          # extended: true

      - name: Build
        run: hugo --minify -v

      - run: sudo apt-get -y install rsync

      - run: rsync --version

      # Deploy to vm-bwg
      - name: Deploy to vm-bwg
        uses: easingthemes/ssh-deploy@v5.1.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_BWG_USER_BLOG }}
          ARGS: "-avz --delete"
          SOURCE: "public/"
          REMOTE_HOST: "66.112.212.90"
          REMOTE_PORT: 27623
          REMOTE_USER: "blog"
          TARGET: "/var/lib/nerdctl/1935db59/volumes/default/nginx-www/_data/"
