name: blog

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      # 如果使用了git submodules
      with:
        submodules: true

    - name: Hugo Actions
      uses: srt32/hugo-action@v0.0.3

    - name: Build
      run: hugo --minify

