name: github pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1  # v2 does not have submodules option now
        with:
          submodules: true
      
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.70.0'
          # extended: true

      - name: Build
        run: hugo --minify -v

      # Deploy to vm-bwg
      - name: Deploy to vm-bwg
        uses: easingthemes/ssh-deploy@v5.1.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_BWG_USER_BLOG }}
          ARGS: "-avz --no-t --delete"
          SOURCE: "public/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: 27623
          REMOTE_USER: "blog"
          #TARGET: "/home/blog/tmp/"
          TARGET: "/var/lib/nerdctl/1935db59/volumes/default/nginx-www/_data/"
          EXCLUDE: "/node_modules/"
          SCRIPT_BEFORE: |
            whoami
            pwd
            ls -al
